name: Publish Angular library to NPM

on:
  push:
    branches:
      - stable

  workflow_dispatch:

jobs:
  build:
    name: Build and publish library
    runs-on: ubuntu-latest
    if: github.repository_owner == 'float-toolkit'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:ci

      - name: Publish on NPM
        run:
          npx npm-publish --access public --registry https://registry.npmjs.org/ --token ${{ secrets.NPM_TOKEN }} dist/package.json

      - name: Publish on GitHub Packages
        run:
          npx npm-publish --access public --registry https://npm.pkg.github.com/ --token ${{ secrets.GITHUB_TOKEN }}
          dist/package.json
