name: Publish Angular library to NPM

on:
  push:
    branches:
      - stable

  workflow_dispatch:

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    if: github.repository_owner == 'float-toolkit'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node_modules
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles("**/package-lock.json") }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:ci

      - name: Upload dist artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  publish:
    name: Publish on NPM and GitHub Packages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Change to dist directory
        run: cd dist

      - name: Publish on NPM
        uses: JS-DevTools/npm-publish@v1.4.3
        with:
          access: public
          registry: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}
          check-version: false

      - name: Publish on GitHub Packages
        uses: JS-DevTools/npm-publish@v1.4.3
        with:
          access: public
          registry: https://npm.pkg.github.com/
          token: ${{ secrets.GITHUB_TOKEN }}
          check-version: false
